version: '3'
services:
  # Application Dockerfile is in the same folder which is .
  app:
    build: .
    command: ["java", "com.napier.sem.App"]

  # Database service
  db:
    build: db/.
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "33060:3306"
