name: A workflow for my Hello World App

on:
  push:
    branches:
      - master

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adopt'
      - name: Run Unit Tests and Generate Coverage
        run: |
          mvn test jacoco:report # Ensure you're generating the coverage report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Not needed for public repos
          files: ./target/site/jacoco/jacoco.xml # Correct path to JaCoCo coverage file
          flags: unittests
          verbose: true

  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adopt'
      - name: Run Integration Tests and CodeCov
        run: |
          docker build -t database ./db 
          docker run --name employees -dp 33060:3306 database
          mvn -Dtest=com.napier.sem.AppIntegrationTest test jacoco:report # Generate coverage
          docker stop employees
          docker rm employees
          docker image rm database
      - name: Upload Integration Test Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Not needed for public repos
          files: ./target/site/jacoco/jacoco.xml # Ensure correct path
          flags: integrationtests
          verbose: true

  build:
    name: Build and Start Using Docker Compose
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adopt'
      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests
          docker compose up --abort-on-container-exit
